version: "3.7"
services:
  db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3200:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
